version: "3.8"
services:
  caddy:
    image: ghcr.io/runeclausen/caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: always

  # Websites
  portfolio:
    image: ghcr.io/runeclausen/portfolio:latest
    restart: always
    
  fremad:
    image: ghcr.io/runeclausen/fremad:latest
    restart: always

  fremadapi:
    image: ghcr.io/runeclausen/fremadapi:latest
    restart: always


  # Services


  # Backing-services
#  postgres:
#    image: postgres:15.2-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-database}
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    restart: always
#    env_file:
#      - config/.env

#  pg-admin:
#    image: dpage/pgadmin4:6
#    environment:
#      PGADMIN_DEFAULT_EMAIL: runesostackclausen@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_LISTEN_PORT: 5050
#    ports:
#      - "5050:5050"

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
