version: "3.8"
services:
  caddy:
    image: ghcr.io/runeclausen/caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: always

  # Websites
  front:
    image: ghcr.io/runeclausen/front:latest
    depends_on:
      - products
    restart: always

  # Services
  back:
    image: ghcr.io/runeclausen/back:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  # Backing-services
  postgres:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-database}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    restart: always

volumes:
  caddy_data:
  caddy_config:
  postgres_data: